namespace MatrixSharp.Api.EventSchemas.Schema.CoreEventSchema
{
	/// <summary>
	///     In addition to the Event fields, Room Events have the following additional
	///     fields.
	/// </summary>
	/// <param name="EventId"> The globally unique event identifier.</param>
	/// <param name="Sender"> Contains the fully-qualified ID of the user who sent this event.</param>
	/// <param name="OriginServerTs">
	///     Timestamp in milliseconds on originating homeserver
	///     when this event was sent.
	/// </param>
	public record SyncRoomEvent<T>(
		T Content,
		string Type,
		string EventId,
		string Sender,
		long OriginServerTs
	) : Event<T>(Content, Type) where T : IContentProperty
	{
		/// <inheritdoc cref="UnsignedData" />
		public UnsignedData? Unsigned { get; init; }
	}

	/// <summary>
	///     Contains optional extra information about the event.
	/// </summary>
	public record UnsignedData
	{
		/// <summary>
		///     The time in milliseconds that has elapsed since the event was
		///     sent. This field is generated by the local homeserver, and may be incorrect
		///     if the local time on at least one of the two servers is out of sync, which can
		///     cause the age to either be negative or greater than it actually is.
		/// </summary>
		public int? Age { get; init; }

		/// <summary>
		///     Optional. The event that redacted this event, if any.
		/// </summary>
		public Event<ContentPropertyPlaceholder>? RedactedBecause { get; init; }

		/// <summary>
		///     The client-supplied transaction ID, if the client being given
		///     the event is the same one which sent it.
		/// </summary>
		public string? TransactionId { get; init; }
	}
}