using System.Text.Json.Serialization;
using MatrixSharp.Models.Events.MatrixEventContent;
using MatrixSharp.Tools;

namespace MatrixSharp.Models.Events
{
	/// <summary>
	///     Room event.
	/// </summary>
	[JsonConverter(typeof(ConverterTools.EventConverter<RoomEvent>))]
	public class RoomEvent : Event
	{
		/// <inheritdoc cref="RoomEvent" />
		public RoomEvent(BaseMatrixEventContent content, string type, string eventId, string sender,
			ulong originServerTs,
			string roomId)
			: base(content, type)
		{
			EventId = eventId;
			Sender = sender;
			OriginServerTs = originServerTs;
			RoomId = roomId;
		}

		/// <summary>
		///     The globally unique event identifier.
		/// </summary>
		[JsonPropertyName("event_id")]
		public string EventId { get; }

		/// <summary>
		///     Contains the fully-qualified ID of the user who sent this event.
		/// </summary>
		[JsonPropertyName("sender")]
		public string Sender { get; }

		/// <summary>
		///     Timestamp in milliseconds on originating homeserver when this event was sent.
		/// </summary>
		[JsonPropertyName("origin_server_ts")]
		public ulong OriginServerTs { get; }

		/// <inheritdoc cref="UnsignedData" />
		[JsonPropertyName("unsigned")]
		public UnsignedData? Unsigned { get; set; }

		/// <summary>
		///     The ID of the room associated with this event. Will not be present on events that arrive through sync, despite
		///     being required everywhere else.
		/// </summary>
		[JsonPropertyName("room_id")]
		public string RoomId { get; }

		/// <summary>
		///     Contains optional extra information about the event.
		/// </summary>
		public class UnsignedData
		{
			/// <summary>
			///     The time in milliseconds that has elapsed since the event was sent. This field is generated by the local
			///     homeserver, and may be incorrect if the local time on at least one of the two servers is out of sync, which can
			///     cause the age to either be negative or greater than it actually is.
			/// </summary>
			[JsonPropertyName("age")]
			public ulong? Age { get; set; }

			/// <summary>
			///     Optional. The event that redacted this event, if any.
			/// </summary>
			[JsonPropertyName("redacted_because")]
			public Event? Event { get; set; }

			/// <summary>
			///     The client-supplied transaction ID, if the client being given the event is the same one which sent it.
			/// </summary>
			[JsonPropertyName("transaction_id")]
			public string? TransactionId { get; set; }
		}
	}
}