namespace MatrixSharp.Api.Identity.Definitions
{
	/// <param name="ClientSecret">
	///     A unique string generated by the client, and used to identify the
	///     validation attempt. It must be a string consisting of the characters
	///     ``[0-9a-zA-Z.=_-]``. Its length must not exceed 255 characters and it
	///     must not be empty.
	/// </param>
	/// <param name="Email"> The email address to validate.</param>
	/// <param name="SendAttempt">
	///     The server will only send an email if the ``send_attempt``
	///     is a number greater than the most recent one which it has seen,
	///     scoped to that ``email`` + ``client_secret`` pair. This is to
	///     avoid repeatedly sending the same email in the case of request
	///     retries between the POSTing user and the identity server.
	///     The client should increment this value if they desire a new
	///     email (e.g. a reminder) to be sent. If they do not, the server
	///     should respond with success but not resend the email.
	/// </param>
	public record RequestEmailValidation(
		string ClientSecret,
		string Email,
		int SendAttempt
	)
	{
		/// <summary>
		///     Optional. When the validation is completed, the identity server will
		///     redirect the user to this URL. This option is ignored when submitting
		///     3PID validation information through a POST request.
		/// </summary>
		public string? NextLink { get; init; }
	}
}