namespace MatrixSharp.Api.Identity.Definitions
{
	/// <param name="ClientSecret">
	///     A unique string generated by the client, and used to identify the
	///     validation attempt. It must be a string consisting of the characters
	///     ``[0-9a-zA-Z.=_-]``. Its length must not exceed 255 characters and it
	///     must not be empty.
	/// </param>
	/// <param name="Country">
	///     The two-letter uppercase ISO-3166-1 alpha-2 country code that the
	///     number in ``phone_number`` should be parsed as if it were dialled from.
	/// </param>
	/// <param name="PhoneNumber"> The phone number to validate.</param>
	/// <param name="SendAttempt">
	///     The server will only send an SMS if the ``send_attempt`` is a
	///     number greater than the most recent one which it has seen,
	///     scoped to that ``country`` + ``phone_number`` + ``client_secret``
	///     triple. This is to avoid repeatedly sending the same SMS in
	///     the case of request retries between the POSTing user and the
	///     identity server. The client should increment this value if
	///     they desire a new SMS (e.g. a reminder) to be sent.
	/// </param>
	public record RequestMsisdnValidation(
		string ClientSecret,
		string Country,
		string PhoneNumber,
		int SendAttempt
	)
	{
		/// <summary>
		///     Optional. When the validation is completed, the identity server will
		///     redirect the user to this URL. This option is ignored when submitting
		///     3PID validation information through a POST request.
		/// </summary>
		public string? NextLink { get; init; }
	}
}