namespace MatrixSharp.Api.Identity.Definitions
{
	/// <param name="Sid">
	///     The session ID. Session IDs are opaque strings generated by the identity
	///     server. They must consist entirely of the characters
	///     ``[0-9a-zA-Z.=_-]``. Their length must not exceed 255 characters and they
	///     must not be empty.
	/// </param>
	public record SessionId(
		string Sid
	);
}